#!/bin/sh

# Source colorscheme
source "${HOME}/.cache/wal/colors.sh"

# Compositor
killall picom 
while pgrep picom > /dev/null;
do
    # Wait for picom process to end
    # Hacky, but apparently there isn't a better way
    # to do this
    sleep 0.1
done;
picom &

# Set cursor
xsetroot -cursor_name left_ptr &

# Set Wallpaper
# hsetroot -cover ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper5.jpg
hsetroot -cover ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper5.jpg
#feh -z --no-fehbg --bg-fill ~/Pictures/Mywallpapers/

# Cache lockscreen 
mantablockscreen -i ~/.config/rice_assets/Images/lockscreen.png&


# Statusbar
killall workspaces    
killall media_info    
killall layout 
polybar &
# $HOME/.config/polybar/launch.sh &

    
# daemons
killall dunst
dunst > /dev/null 2> /dev/null &
thunar --daemon&
killall sxhkd
sxhkd -c ~/.config/bspwm/sxhkdrc > /dev/null 2> /dev/null&
